# Generated by Django 5.0.6 on 2026-08-14 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "price_per_month_tiyin",
                    models.PositiveIntegerField(
                        help_text="Bir oylik narx TIYINDA (100 000 so'm = 10000000)"
                    ),
                ),
                (
                    "trial_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Avtomatik sinov kunlari. 0 = faqat admin qo'lda beradi.",
                    ),
                ),
                (
                    "grace_days",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Muddat tugagandan keyin qo'shimcha ishlash kunlari",
                    ),
                ),
                (
                    "pending_hold_days",
                    models.PositiveIntegerField(
                        default=5, help_text="Chek yuborilgandan keyin kutish kunlari"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tarif",
                "verbose_name_plural": "Tariflar",
            },
        ),
        migrations.CreateModel(
            name="AdminSetting",
            fields=[
                (
                    "key",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("value", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin sozlamasi",
                "verbose_name_plural": "Admin sozlamalari",
            },
        ),
        migrations.CreateModel(
            name="PaymentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("months", models.PositiveIntegerField()),
                ("amount_tiyin", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Yuborildi"),
                            ("CARD_ISSUED", "Karta berildi"),
                            ("RECEIPT_UPLOADED", "Chek yuborildi"),
                            ("CONFIRMED", "Tasdiqlandi"),
                            ("REJECTED", "Rad etildi"),
                            ("EXPIRED", "Javobsiz qoldi"),
                        ],
                        db_index=True,
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("card_issued_at", models.DateTimeField(blank=True, null=True)),
                ("receipt_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "receipt_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TELEGRAM", "Telegram"),
                            ("EMAIL", "Email"),
                            ("OTHER", "Boshqa"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("admin_note", models.TextField(blank=True)),
                (
                    "external_tx_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_payment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_requests",
                        to="billing.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "To'lov so'rovi",
                "verbose_name_plural": "To'lov so'rovlari",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("hold_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_reminder_days_left", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obuna",
                "verbose_name_plural": "Obunalar",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("months", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("TRIAL", "Sinov muddati"),
                            ("PAYMENT", "To'lov"),
                            ("ADMIN_GRANT", "Admin bepul berdi"),
                            ("MIGRATION", "Tizim joriy qilinganda"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CASH", "Naqd"),
                            ("CARD_TRANSFER", "Kartaga o'tkazma"),
                            ("CLICK", "Click"),
                            ("PAYME", "Payme"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("amount_tiyin", models.PositiveIntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="period",
                        to="billing.paymentrequest",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="periods",
                        to="billing.subscription",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="periods",
                        to="billing.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obuna davri",
                "verbose_name_plural": "Obuna davrlari (jurnal)",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subscription", "-end_date"],
                        name="billing_sub_subscri_1f1a23_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="subscriptionperiod",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("payment_method__isnull", False), ("source", "PAYMENT")),
                    models.Q(
                        models.Q(("source", "PAYMENT"), _negated=True),
                        ("payment_method__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="payment_method_only_for_payment_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionperiod",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gt", models.F("start_date"))),
                name="period_end_after_start",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrequest",
            index=models.Index(
                fields=["user", "-requested_at"], name="billing_pay_user_id_d4d359_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentrequest",
            constraint=models.CheckConstraint(
                check=models.Q(("months__in", (1, 3, 6, 12))),
                name="payment_request_months_allowed",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["REQUESTED", "CARD_ISSUED", "RECEIPT_UPLOADED"])
                ),
                fields=("user",),
                name="one_open_payment_request_per_user",
            ),
        ),
    ]
