# Generated by Django 5.0.6 on 2026-02-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_lesson_content_lesson_practice_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        help_text="Topshiriq matni (HTML/Markdown qo'llab-quvvatlaydi)"
                    ),
                ),
                (
                    "initial_code",
                    models.TextField(
                        default="// Kodni shu yerga yozing...",
                        help_text="Muharrirdagi dastlabki kod",
                    ),
                ),
                (
                    "solution_code",
                    models.TextField(
                        blank=True, help_text="To'g'ri javob kodi (tekshirish uchun)"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Oson", "Oson"),
                            ("O'rtacha", "O'rtacha"),
                            ("Qiyin", "Qiyin"),
                        ],
                        default="Oson",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
