# Generated by Django 5.0.6 on 2026-02-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_challenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="time_limit",
            field=models.PositiveIntegerField(
                default=20, help_text="Testni topshirish vaqti (minutda)"
            ),
        ),
    ]
