# Generated by Django 5.0.6 on 2026-02-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_quiz_time_limit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Loyiha uchun mockup yoki rasm URL",
                        null=True,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Entry", "Entry"),
                            ("Pro", "Pro"),
                            ("Architect", "Architect"),
                        ],
                        default="Entry",
                        max_length=50,
                    ),
                ),
                (
                    "tech_stack",
                    models.CharField(
                        help_text="Texnologiyalar (vergul bilan ajrating: React, Node.js, JS)",
                        max_length=255,
                    ),
                ),
                ("demo_url", models.URLField(blank=True, null=True)),
                ("repo_url", models.URLField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
