# Generated by Django 5.0.6 on 2026-08-14 06:32

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_quizresult"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quizresult",
            name="attempts",
            field=models.PositiveIntegerField(default=1, help_text="Nechinchi urinish"),
        ),
        migrations.AddField(
            model_name="quizresult",
            name="correct_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quizresult",
            name="total_questions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="quizresult",
            name="score_percentage",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="quizresult",
            unique_together={("user", "quiz")},
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["user", "is_completed"], name="core_userpr_user_id_9dc9fe_idx"
            ),
        ),
    ]
