# Generated by Django 5.0.6 on 2026-08-14 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_quizresult_attempts_quizresult_correct_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="is_free",
            field=models.BooleanField(
                default=False,
                help_text="Belgilansa, obunasiz ham ochiq bo'ladi (tanishtiruv darsi)",
                verbose_name="Bepul dars",
            ),
        ),
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_resets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Parol tiklash kodi",
                "verbose_name_plural": "Parol tiklash kodlari",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "used_at"],
                        name="core_passwo_user_id_ce3c36_idx",
                    )
                ],
            },
        ),
    ]
