# Generated by Django 5.0.6 on 2026-08-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_lesson_is_free_passwordreset"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=150)),
                (
                    "ip",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("successful", models.BooleanField(default=False)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Tizimga kirish"),
                            ("RESET", "Parolni tiklash"),
                        ],
                        db_index=True,
                        default="LOGIN",
                        max_length=10,
                    ),
                ),
                ("user_agent", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Login urinishi",
                "verbose_name_plural": "Login urinishlari",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["purpose", "username", "successful", "-created_at"],
                        name="core_logina_purpose_e40460_idx",
                    ),
                    models.Index(
                        fields=["purpose", "ip", "successful", "-created_at"],
                        name="core_logina_purpose_73f0aa_idx",
                    ),
                ],
            },
        ),
    ]
