# Generated by Django 5.0.6 on 2026-08-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_profile_telegram_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="language",
            field=models.CharField(
                choices=[("python", "Python"), ("javascript", "JavaScript")],
                default="python",
                max_length=20,
                verbose_name="Til",
            ),
        ),
    ]
