# Generated by Django 5.0.6 on 2026-08-14 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_mentormessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name": "Test", "verbose_name_plural": "Testlar"},
        ),
        migrations.AddField(
            model_name="quiz",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="quiz",
            name="is_generated",
            field=models.BooleanField(
                default=False,
                help_text="Avtomatik yozilgan. Nashrdan oldin tekshirilishi shart.",
                verbose_name="Model generatsiya qilgan",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Olib tashlansa o'quvchi bu testni ko'rmaydi (qoralama)",
                verbose_name="Nashr qilingan",
            ),
        ),
    ]
