# Generated by Django 5.0.6 on 2026-08-15 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_quiz_options_quiz_created_at_quiz_is_generated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="theory",
            field=models.TextField(
                default="",
                help_text="Oddiy matn. Bezaklar: ## sarlavha, **qalin**, `kod`, - ro'yxat, > eslatma, ``` kod bloki ```",
                verbose_name="Dars matni",
            ),
        ),
        migrations.CreateModel(
            name="LessonImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="lesson_images/", verbose_name="Rasm"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Rasm tagida chiqadigan matn",
                        max_length=300,
                        verbose_name="Izoh",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Rasm ochilmasa yoki ekran o'qigich uchun tavsif",
                        max_length=200,
                        verbose_name="Muqobil matn",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dars rasmi",
                "verbose_name_plural": "Dars rasmlari",
                "ordering": ["order", "id"],
            },
        ),
    ]
