# Generated by Django 5.0.6 on 2026-08-15 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_profile_approved_at_profile_approved_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        blank=True,
                        help_text="Otasi / Onasi / Vasiysi",
                        max_length=50,
                        verbose_name="Kimligi",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_parent_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ota-ona",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ota-ona bog'lanishi",
                "verbose_name_plural": "Ota-ona bog'lanishlari",
            },
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "seconds",
                    models.PositiveIntegerField(default=0, verbose_name="Soniya"),
                ),
                ("lessons_completed", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "O'quv vaqti",
                "verbose_name_plural": "O'quv vaqtlari",
                "ordering": ["-date"],
            },
        ),
        migrations.AddConstraint(
            model_name="parentlink",
            constraint=models.UniqueConstraint(
                fields=("parent", "student"), name="one_link_per_parent_student"
            ),
        ),
        migrations.AddConstraint(
            model_name="parentlink",
            constraint=models.CheckConstraint(
                check=models.Q(("parent", models.F("student")), _negated=True),
                name="parent_is_not_student",
            ),
        ),
        migrations.AddIndex(
            model_name="studysession",
            index=models.Index(
                fields=["user", "-date"], name="core_studys_user_id_ade772_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studysession",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="one_study_row_per_day"
            ),
        ),
    ]
