# Generated by Django 5.0.6 on 2026-08-14 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_telegramlinktoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentrequest",
            name="external_tx_id",
        ),
        migrations.CreateModel(
            name="GatewayTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("PAYME", "Payme"), ("CLICK", "Click")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("external_id", models.CharField(max_length=100)),
                ("amount_tiyin", models.PositiveIntegerField()),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (1, "Yaratildi"),
                            (2, "To'landi"),
                            (-1, "Bekor qilindi"),
                            (-2, "To'lovdan keyin bekor qilindi"),
                        ],
                        db_index=True,
                        default=1,
                    ),
                ),
                ("external_created_ms", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("performed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.IntegerField(blank=True, null=True)),
                ("raw_request", models.JSONField(blank=True, null=True)),
                (
                    "payment_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gateway_transactions",
                        to="billing.paymentrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "To'lov tizimi tranzaksiyasi",
                "verbose_name_plural": "To'lov tizimi tranzaksiyalari",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["payment_request", "state"],
                        name="billing_gat_payment_3b1371_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="gatewaytransaction",
            constraint=models.UniqueConstraint(
                fields=("provider", "external_id"), name="unique_gateway_transaction"
            ),
        ),
    ]
