# Generated by Django 5.0.6 on 2026-08-15 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_remove_paymentrequest_external_tx_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="paymentrequest",
            name="payment_request_months_allowed",
        ),
        migrations.AddConstraint(
            model_name="paymentrequest",
            constraint=models.CheckConstraint(
                check=models.Q(("months__in", (1,))),
                name="payment_request_months_allowed",
            ),
        ),
    ]
