# Generated by Django 5.0.6 on 2026-08-16 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing",
            "0004_remove_paymentrequest_payment_request_months_allowed_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrequest",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests_made_for_others",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kim boshladi",
            ),
        ),
    ]
