# Generated by Django 5.0.6 on 2026-08-14 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PanelMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("ONE", "Bitta o'quvchi"),
                            ("ALL", "Hamma (Telegrami ulanganlar)"),
                            ("ACTIVE", "Obunasi faollar"),
                            ("EXPIRING", "Muddati 7 kunda tugaydiganlar"),
                            ("EXPIRED", "Obunasi tugaganlar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Navbatda"),
                            ("DONE", "Yuborildi"),
                            ("FAILED", "Yetkazilmadi"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("total", models.PositiveIntegerField(default=0)),
                ("delivered", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="panel_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="panel_messages_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Panel xabari",
                "verbose_name_plural": "Panel xabarlari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PanelDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.CharField(blank=True, max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Navbatda"),
                            ("SENT", "Yuborildi"),
                            ("FAILED", "Xato"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=200)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panel_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="panel.panelmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xabar yetkazish",
                "verbose_name_plural": "Xabar yetkazishlar",
                "indexes": [
                    models.Index(
                        fields=["message", "state"],
                        name="panel_panel_message_295629_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="paneldelivery",
            constraint=models.UniqueConstraint(
                fields=("message", "user"), name="one_delivery_per_user_per_message"
            ),
        ),
    ]
