# Generated by Django 5.0.6 on 2026-02-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="content",
        ),
        migrations.AddField(
            model_name="lesson",
            name="practice_code",
            field=models.TextField(
                blank=True, default="", help_text="Amaliy kod namunalari uchun"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="theory",
            field=models.TextField(
                default="",
                help_text="Nazariy ma'lumotlar uchun (HTML/Markdown qo'llab-quvvatlaydi)",
            ),
        ),
    ]
