# Generated by Django 5.0.6 on 2026-02-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_newstudent_userprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Dars videosini yuklash",
                null=True,
                upload_to="lesson_videos/",
            ),
        ),
    ]
