# Generated by Django 5.0.6 on 2026-08-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Bir martalik havola orqali avtomatik to'ldiriladi",
                max_length=32,
                verbose_name="Telegram chat ID",
            ),
        ),
    ]
