# Generated by Django 5.0.6 on 2026-08-15 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def approve_existing_students(apps, schema_editor):
    """
    MAVJUD o'quvchilarga ruxsatni AVTOMATIK beradi.

    NEGA KERAK: yangi maydonning standart qiymati `False`. Migratsiya
    shusiz o'tsa, allaqachon ro'yxatdan o'tgan va to'lagan o'quvchilar
    ertalab turib kirish yopilganini ko'rardi. Yangi qoida FAQAT
    bundan keyingi ro'yxatdan o'tishlarga tegishli.
    """
    Profile = apps.get_model('core', 'Profile')
    Profile.objects.update(is_approved=True)


def unapprove_all(apps, schema_editor):
    """Orqaga qaytarish: maydon o'chiriladi, bu yerda ish yo'q."""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_lesson_theory_lessonimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ruxsat vaqti"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_students",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kim ruxsat berdi",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Olib tashlansa o'quvchi darslarni ko'rmaydi",
                verbose_name="Ruxsat berilgan",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="rejection_reason",
            field=models.TextField(blank=True, verbose_name="Rad etish sababi"),
        ),
        # Maydonlar QO'SHILGANDAN KEYIN ishlaydi — tartib muhim
        migrations.RunPython(approve_existing_students, unapprove_all),
    ]
