# Generated by Django 5.0.6 on 2026-08-16 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_parentlink_studysession_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="password_resets_done",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kim tikladi",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_password_resets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parol tiklash yozuvi",
                "ordering": ["-created_at"],
            },
        ),
    ]
