# Generated by Django 5.0.6 on 2026-08-19 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_passwordresetlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="expected_output",
            field=models.TextField(
                blank=True,
                help_text="Kod to'g'ri bo'lsa chiqadigan matn. Bo'sh bo'lsa tekshirish o'chadi.",
                verbose_name="Kutilgan natija",
            ),
        ),
        migrations.CreateModel(
            name="ChallengeProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solved_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="core.challenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Topshiriq natijasi",
                "verbose_name_plural": "Topshiriq natijalari",
                "indexes": [
                    models.Index(
                        fields=["user", "solved_at"],
                        name="core_challe_user_id_a84a8e_idx",
                    )
                ],
                "unique_together": {("user", "challenge")},
            },
        ),
    ]
